### ISSUE TITLE
Mac TypeError  this[#reliableWindow].entries is not iterable

### ISSUE THREAD

**Issue by KnightSec-Official** [HerryYT/JSPrismarine#34]
```
[02:33:27] info: Loaded world as default world!
[02:33:27] debug: World world succesfully loaded!
[02:33:27] info: JSPrismarine is now listening port 19132
[02:33:27] debug: Loaded 44 Minecraft packets!
[02:33:27] debug: Loaded 17 packet handlers!
/Users/Myname/Downloads/JSPrismarine-master/node_modules/jsraknet/connection.js:305
                    let windows = [...this.#reliableWindow.entries]
                                                           ^

TypeError: this[#reliableWindow].entries is not iterable
    at Connection.receivePacket (/Users/Myname/Downloads/JSPrismarine-master/node_modules/jsraknet/connection.js:305:60)
    at Connection.handleDatagram (/Users/Myname/Downloads/JSPrismarine-master/node_modules/jsraknet/connection.js:243:18)
    at Connection.receive (/Users/Myname/Downloads/JSPrismarine-master/node_modules/jsraknet/connection.js:179:25)
    at Listener.handle (/Users/Mynamel/Downloads/JSPrismarine-master/node_modules/jsraknet/listener.js:81:24)
    at Socket.<anonymous> (/Users/Myname/Downloads/JSPrismarine-master/node_modules/jsraknet/listener.js:55:18)
    at Socket.emit (events.js:209:13)
    at UDP.onMessage [as onmessage] (dgram.js:853:8)
```

Gives this when i try to enter from ps4... tho the server is available... but disconnects me some times when i attempt to join.

Also when i connect, it spawns me with  no head, no health bar, just hunger...

**Comment by Bavfalcon9** [comment]
Fixed in: [`90beeb3` (#3)](https://github.com/HerryYT/JSRakNet/pull/3/commits/90beeb37928a677ebc84bd3756b854fb1018b293)
